version: "2"

checks:
  method-complexity:
    config:
      threshold: 6

plugins:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          patterns:
            - test/*.js

  eslint:
    enabled: true

  fixme:
    enabled: true

  nodesecurity:
    enabled: true

  markdownlint:
    enabled: true

  shellcheck:
    enabled: true

  editorconfig:
    enabled: true

exclude_patterns:
  - .nyc_output/**
  - coverage/**
  - node_modules/**
